# Generated by Django 5.2.4 on 2025-11-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
