# Generated by Django 5.2.4 on 2025-11-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='querie',
            new_name='query',
        ),
    ]
