# Generated by Django 5.2.4 on 2025-12-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_querie_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
